pool:
  vmImage: ubuntu-latest
trigger: 
- feature-ms-raulRiquelme-labFinal 
steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'jacocoTestReport'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: true
  displayName: 'Build'
- task: CopyFiles@2
  displayName: 'Prepare artifact'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
        **/build/libs/*.jar
        **/build/**/*.xml
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: appJar
    publishLocation: 'Container'
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'appJar'
    downloadPath: '$(Pipeline.Workspace)'
  displayName: Descarga Jar
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonarcloud'
    organization: 'fundamentos-devops-usach'
    #scannerMode: 'MSBuild'
    projectKey: 'Fundamentos-DevOps-Usach_microservicio-spring'
    projectName: 'microservicio-spring'
    extraProperties: |
        sonar.coverage.jacoco.xmlReportPaths=$(Pipeline.Workspace)/appJar/build/reports/jacoco/test/jacocoTestReport.xml

- task: Gradle@3
  inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'jacocoTestReport'
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: true
      sqGradlePluginVersionChoice: 'specify'
      sonarQubeGradlePluginVersion: '3.3'
  displayName: 'SonarQube run'
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: sonarcloud-buildbreaker@2
  inputs:
    SonarCloud: 'Sonarcloud'
    organization: 'fundamentos-devops-usach'
- task: DownloadBuildArtifacts@0
  inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'appJar'
      downloadPath: '$(Pipeline.Workspace)'
      
- script: 'mkdir -p build/libs; mv $(Pipeline.Workspace)/appJar/build/libs/ build/; chmod -R 555 build/libs'
  displayName: 'Artifact prepare' 
- task: Docker@2
  inputs:
    containerRegistry: 'DockerRegistryFundamentosDevOps'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'DockerRegistryFundamentosDevOps'
    repository: 'fundamentos-dev-ops-usach'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'