pool:
  vmImage: ubuntu-latest
trigger: 
- feature-ms-raulRiquelme-labFinal 
steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build jacocoTestReport'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: true
  displayName: 'Build'
- task: CopyFiles@2
  displayName: 'Prepare artifact'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
        **/build/libs/*.jar
        **/build/**/*.xml
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: appJar
    publishLocation: 'Container'
- task: PublishCodeCoverageResults@1
  displayName: 'Publish artifact'
  inputs:
    codeCoverageTool: 'JaCoCo' 
    summaryFileLocation: '$(Build.ArtifactStagingDirectory)/reports/jacoco/test/jacocoTestReport.xml'
    reportDirectory: '$(Build.ArtifactStagingDirectory)/reports/jacoco/test/html'
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'appJar'
    downloadPath: '$(Pipeline.Workspace)'
  displayName: Descarga Jar
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonarcloud'
    organization: 'fundamentos-devops-usach'
    #scannerMode: 'MSBuild'
    projectKey: 'Fundamentos-DevOps-Usach_microservicio-spring'
    projectName: 'microservicio-spring'
    extraProperties: |
        sonar.coverage.jacoco.xmlReportPaths=$(Pipeline.Workspace)/appJar/build/reports/jacoco/test/jacocoTestReport.xml

- task: Gradle@3
  inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'jacocoTestReport'
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: true
      sqGradlePluginVersionChoice: 'specify'
      sonarQubeGradlePluginVersion: '3.3'
  displayName: 'SonarQube run'
